server:
  port: 8083

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/budgetwise_transaction?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      httpclient:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  circuitbreaker:
    enabled: true

