server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**

            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/api/accounts/**

            - id: budget-service
              uri: lb://account-service
              predicates:
                - Path=/api/budgets/**

            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/api/transactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: budgetwisesecretkey2024budgetwisesecretkey2024xx